### ISSUE TITLE
Erro Expo

### ISSUE THREAD

**Issue by brunopadua05** [juninmd/unifacef-react-native#61]
Boa tarde!

Alguém já se deparou com este erro, estou utilizando o Expo como emulador.
![screenshot](https://user-images.githubusercontent.com/46328409/77932847-76a51000-7284-11ea-8f44-1172d8677a85.png)

**Comment by brunopadua05** [comment]
E Linux Mint de sistema operacional.

**Comment by juninmd** [comment]
@brunopadua05 tente executar esses comandos:
```
$ echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
```
e depois
```
$ sudo sysctl -p 
```

Depois tente novamente.

**Comment by brunopadua05** [comment]
Obrigado.
